
//list any import classes here.
import com.eastcom.ilink.common.databus.DataBus;
import com.eastcom.ilink.businessprocess.res.rule.bean.TransRule;
import com.eastcom.ilink.businessprocess.res.rule.bean.TransRuleParam;


//declare any global variables here


rule "002.0020010.rule.0021000_rule1" 

    when
        //conditions
        dataBus : DataBus()
    then
         //actions
        //特殊数据域处理规则
        dataBus.set("special_data_handle_process","false");
        
        //商户校验
        dataBus.set("merchant_check_process","false");
        
        //终端校检
        dataBus.set("terminal_check_process","false");
        
        //原交易验证匹配规则。
        dataBus.set("sub_data_exchange_process", "false");
        
        //特殊响应码处理
        dataBus.set("sub_special_respcode_handler_process", "false");
        
        //特殊字段处理规则1
        dataBus.set("special_field_rule1", "0021000_special_field_rule1");
        
        //特殊字段处理规则2
        dataBus.set("special_field_rule2", "002.common.flow.empty");
        
        //设置字段缺省值
        //主账号
		dataBus.set("account_no", "164392260018081495");
		//受卡方所在时间
		dataBus.set("term_time", "094212");
		//受卡方所在日期
		dataBus.set("term_date", "0530");
		//卡有效期
		dataBus.set("expire_date", "0512");
		//清算日期
		dataBus.set("settle_date", "0530");
		//授权码
		dataBus.set("auth_resp", "123456");
		//应答码
		dataBus.set("p_front_resp_code", "12");
		//附加响应数据(变长，设定为8位)
		dataBus.set("add_resp_data", "0812345678");
		//自定义域（63域）国际IC卡代码
		dataBus.set("international_ic_corp_code", "012");
		//自定义域2(子定义域)
		dataBus.set("add_data", "0811110000");
        

end

