
//list any import classes here.
import com.eastcom.ilink.common.databus.DataBus;
import com.eastcom.ilink.businessprocess.res.rule.bean.TransRule;
import com.eastcom.ilink.businessprocess.res.rule.bean.TransRuleParam;


//declare any global variables here


rule "002.0025205.rule.0025205_rule1" 

    when
        //conditions
        dataBus : DataBus()
    then
        //actions

end

