<?xml version="1.0" encoding="UTF-8"?>

<message direction="decode" type="xml"> 
  <field type="string" codec="binary2Str('GBK')" name="numno" desc="客户编号" xpath="/ILINK/REQUEST/NUMNO"/>
  <field type="string" codec="binary2Str('GBK')" name="husnit" desc="核算单位" xpath="/ILINK/REQUEST/HSUNIT"/>
  <field type="string" codec="binary2Str('GBK')" name="caerare" desc="电费年月" xpath="/ILINK/REQUEST/CARFARE"/>
</message>
