<?xml version="1.0" encoding="UTF-8"?>

<message direction="decode" type="xml"> 
  <field type="string" codec="binary2Str('GBK')" name="work_date" desc="平台日期" xpath="/ILINK/REQUEST/WORK_DATE"/>
  <field type="string" codec="binary2Str('GBK')" name="bat_no" desc="批次号" xpath="/ILINK/REQUEST/BAT_NO"/>
  <field type="string" codec="binary2Str('GBK')" name="crp_cod" desc="单位编号" xpath="/ILINK/REQUEST/CRP_COD"/>
  <field type="string" codec="binary2Str('GBK')" name="itm_cod" desc="项目编号" xpath="/ILINK/REQUEST/ITM_COD"/>
</message>
